### ISSUE TITLE
[Bug] Vanished users can be messaged.

### ISSUE THREAD

**Issue by ItzSave** [Aust1n46/VentureChat#10]
To recreate:

    - Enter /vanish on an account.
    - Have another account without permission to see vanished users.
    - The default account should use /msg "vanished player's name"

Expected Behavior:

    - Default users should not be able to message the vanished users and should return a user as offline.
    
    
    
  Plugins used:
  - AdvancedVanish
  - VentureChat
  - Essentials

**Comment by williamd5** [comment]
This is because "vanishing" is just a trick. The player is still connected server-side and without explicit integration with the vanish plugin, there isn't a way to check if the player is vanished.
I used SuperVanish and simply developed a custom `/msg` and `/r` functionality.

**Comment by williamd5** [comment]
> 

Well, developing your own `/msg` command might be the easiest solution. We have cross-server `/msg` and `/r` so to respect vanished players, what we did was:
1. Use your vanish plugin's API to listen for a "vanish/unvanish" event and broadcast it to the proxy using a plugin message. If the API doesn't have an event, you could override the vanish command with your own one which vanishes the player via the API and sends a message to the proxy. Make sure to check vanish status on join as well. If your vanish plugin uses a DB all of this would be unnecessary and you could just check its DB to filter currently vanished players.
2. The `/msg` command is very simple - it just sends a message to 2 players (sender and recipient). To enable `/r` you can store a hashmap in memory like `Hashmap<UUID, UUID>` where the 1st UUID is the sender and the latter is the target. So when someone sends a message, you just `.put()` both `target uuid, sender` and `sender uuid, target uuid` so both players can `/r` each other
3. In your `/msg` command you can check if the player is in your "vanished players" list and if they are, treat them as offline.

**Comment by Aust1n46** [comment]
Like what was already said, there is no way for VentureChat to "know" if someone is vanished over BungeeCord.

Single server usage should have native vanish support if the vanish plugin is using the Bukkit API "hiding" feature.

If someone ever makes a unified vanish API (like Vault is for permissions), I might be able to implement a proper hook.
Or if there is one vanish plugin that is superiorly popular over the others.
