### ISSUE TITLE
IllegalStateException with >1.20.2 clients on Waterfall

### ISSUE THREAD

**Issue by mercurialmusic** [Aust1n46/VentureChat#101]
I'm not sure if this is a VentureChat or a ViaVersion or a Waterfall thing so I'm putting it everywhere to see if it sticks, but looks like there may be a couple related issues already. Starting a new one since the use case is at least slightly different.

Using anything newer than a 1.20.2 client, players are being kicked from the network on any global chat events on bungee-wide channels with the following error:

https://gist.github.com/mercurialmusic/4da51fb572ee4e4b689d09cfcd11128e

I'm using VentureChat 3.6.0 on git-Paper-318 (MC: 1.20.2)/git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556 with ViaVersion-4.9.3-SNAPSHOT-b750 on the Paper servers only.

**Comment by Aust1n46** [comment]
I don't know what I can do here to fix this.  I'm sending packet data using ProtocolLib for 1.20.2. (Or whatever version the server is running).  I don't know how I could control how the packet data is translated for different client versions connecting.

I'll have to test against 1.20.3 servers when I get the chance.

**Comment by mercurialmusic** [comment]
After responses from ViaVersion it seems like it's on their end, not yours. They said it may be a Bungee issue, and of course Bungee says it's ViaVersion. I did get some weird JSON error spam that looked like it was from VentureChat (it was the VC channel formatting), but I think it was just Bungee or ViaVersion derping. Regardless, I wasn't the only one having the issue and not everyone who was having the issues had VentureChat, so I think it's safe to close this for now. I'll open a new one if I get any more info that points here, but I doubt it. Sorry for the bother.
