### ISSUE TITLE
Feature request: Support 1.20.4 Server

### ISSUE THREAD

**Issue by Pantera07** [Aust1n46/VentureChat#102]
It doesn't work.

**Comment by Aust1n46** [comment]
Chat packet fields have been changed.  Don't know what they were changed to yet to apply a fix.

**Comment by chrismwiggs** [comment]
Any update on this? I've had to ditch VC while this is figured out. Anything I can do to help troubleshoot?

**Comment by Aust1n46** [comment]
3.7.0 released
