### ISSUE TITLE
Issue with 1.19

### ISSUE THREAD

**Issue by Razorxd1993** [Aust1n46/VentureChat#12]
The following error appears :
https://pastebin.com/6QQvV24i

all plugins are the latest versions.

What can be done about it ?

Kind regards

**Comment by comonier** [comment]
same here - trying to fount another chat plugin to replace it, but does not exist

**Comment by osfanbuff63** [comment]
Be patient, @Aust1n46 will get to it when they have time. Personally with that issue I'd try using the [latest ProtocolLib dev build](https://ci.dmulloy2.net/job/ProtocolLib/) and see if it works then

**Comment by Razorxd1993** [comment]
@comonier i Switch to Bungeechat.
The newest protocolib/protocolize don't fix thus Bug.

**Comment by Aust1n46** [comment]
This was fixed in https://www.spigotmc.org/resources/venturechat.771/update?update=461106
