### ISSUE TITLE
Unable to cancel chat message

### ISSUE THREAD

**Issue by coralpapa** [Aust1n46/VentureChat#20]
https://github.com/Aust1n46/VentureChat/blob/38746624d931365fa790b655b7caf6083bf9ba55/src/main/java/mineverse/Aust1n46/chat/listeners/ChatListener.java#L47

can you reduce the priority of AsyncPlayerChatEvent Listener
i've tried canceling this event and regardless it still sends in chat:

	@EventHandler(priority = EventPriority.HIGHEST)
	public void stopChat(AsyncPlayerChatEvent event) {

		event.setCancelled(true);
		
	}

**Comment by Aust1n46** [comment]
Read the documentation: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/EventPriority.html

You should use a lower priority if you want to cancel the event before it reaches VentureChat.

**Comment by DenisMasterHerobrine** [comment]
Switching the priority works, but only when using Bukkit's AsyncPlayerChatEvent. Using AsyncChatEvent from Paper doesn't cancels the message, however does nearly the same, but using Component.

Feel free to correct me if it works with AsyncChatEvent from Paper.

**Comment by Aust1n46** [comment]
VentureChat uses only Spigot events.  You'll have to work with that.  I'm not forcing Paper usage.  The Spigot chat event fits my intended usage better as it currently stands.

**Comment by coralpapa** [comment]
Yeah i'm only using Spigot Events. 
I tried without using priority first then added priority when it didn't cancel.
but there was an error and it wasn't even getting to the cancel line, that is why the event wasn't getting canceled. 
Sorry about that.
I did leave in priority and set it as High.
