### ISSUE TITLE
Disable [Global] prefix on DiscordSRV

### ISSUE THREAD

**Issue by belphegorspn** [Aust1n46/VentureChat#21]
Is there any way I can disable the [Global] prefix when someone chats on discord to minecraft?
![image](https://user-images.githubusercontent.com/66054833/176811852-e443b0c0-5e2e-4f28-ae4c-df36a5c31357.png)

**Comment by Aust1n46** [comment]
You should check your Discord to Minecraft plugin's config.

**Comment by diademiemi** [comment]
Were you able to resolve this? @belphegorspn

**Comment by Aust1n46** [comment]
> Were you able to resolve this? @belphegorspn

My closing reply is the resolution.  DiscordSRV messages are configured in their config.

**Comment by diademiemi** [comment]
It gets it from the aliases within VentureChat, so I was wondering if they found a way to disable it. I'll look through both DiscordSRVs and VentureChats code and see where it comes from..

**Comment by Aust1n46** [comment]
> It gets it from the aliases within VentureChat, so I was wondering if they found a way to disable it. I'll look through both DiscordSRVs and VentureChats code and see where it comes from..

It's in the DiscordSRV config...  Sure the default message format uses a placeholder from VentureChat, but the solution is to edit the message format to remove the placeholder you don't want to use.  Not to edit what populates the placeholder value.
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/messages/en.yml#L98

**Comment by diademiemi** [comment]
Thank you, that's what I was looking for
