### ISSUE TITLE
[Feature Request] Send player messages as system messages

### ISSUE THREAD

**Issue by DaMarine** [Aust1n46/VentureChat#31]
So forgive me being slightly OOTL with this, I've tried my best to keep up with the chat reporting saga but it has felt like we're in an ever changing landscape with it

My understanding is that system signed messages cannot be reported, and have the least obtrusive grey border in the chat window. Will VentureChat allow server owners to mitigate this player reporting tool by having an opt-in setting for all messages be sent as system messages?

**Comment by dlee13** [comment]
It is already doing that on 1.19 servers since the last commit.

**Comment by DaMarine** [comment]
Can confirm this does appear to be native behaviour.
