### ISSUE TITLE
VersionHandler now requires usage of the latest ProtocolLib even with older server versions

### ISSUE THREAD

**Issue by Aust1n46** [Aust1n46/VentureChat#35]
@dlee13 https://www.spigotmc.org/threads/venturechat.24005/page-527#post-4464461
Issue posted on Spigot.  Using ProtocolLibs version enum in the VersionHandler makes VentureChat dependent on the latest version of ProtocolLib at all times even if they're using older game versions.

I will open a PR to refactor it.

**Comment by dlee13** [comment]
Oops, I'd mistakenly just assumed that latest ProtocolLib still works on older Minecraft.
