### ISSUE TITLE
[Feature request] Unicode support

### ISSUE THREAD

**Issue by Fer-Jgu** [Aust1n46/VentureChat#4]
Support for unicode chars to use with resource packs
For example:
` \uEffb` becomes ![image](https://user-images.githubusercontent.com/76271548/164878335-c1b677a2-139d-412f-943c-5453a8548e6d.png)
...
So I can do something like 
![image](https://user-images.githubusercontent.com/76271548/164878348-1abe989b-7a97-4da6-b091-36be12c930f4.png)
using only Venture :)

**Comment by williamd5** [comment]
You could simply copy-paste the raw character. `\uEffb` is ``

**Comment by Fer-Jgu** [comment]
Where can I get that? xd

**Comment by Fer-Jgu** [comment]
Thanks, it actually worked c:
