### ISSUE TITLE
Problems with "mcMMO" Party Commands

### ISSUE THREAD

**Issue by Angsimosaurus** [Aust1n46/VentureChat#40]
With "VentureChat" present, when you enter the "party" command, you receive an error that you do not have permission.

"You do not have permission for this command!"

![image](https://user-images.githubusercontent.com/79510039/187076527-c1f6d632-04eb-4711-a60c-84929095deb0.png)

**Comment by Aust1n46** [comment]
VentureChat's commands will override other plugins commands.  Disable VentureChat's command in the commands.yml config file if you don't want to use.

**Comment by Angsimosaurus** [comment]
> VentureChat's commands will override other plugins commands. Disable VentureChat's command in the commands.yml config file if you don't want to use.

That's how you did it! Thank you. It's solved
