### ISSUE TITLE
[Feature Request] McMMO Party Chat Support

### ISSUE THREAD

**Issue by MasonX3** [Aust1n46/VentureChat#45]
Hello, I was wondering if there was a chance for McMMO Party Chat support to be added to VentureChat.
It's been a request on my server by my players, I think it could be a pretty good addition as well.

**Comment by Aust1n46** [comment]
It already is supported.  Disable the VentureChat party command in the commands.yml config and the mcmmo party command will take priority.

**Comment by MasonX3** [comment]
While this allows McMMO's party chat to take priority, I don't think that's exactly what I was hoping for. I have already overwritten the party command separately via the default commands.yml. I was hoping there would be an option similar to how Faction and TownyChat were handled so that I didn't have to go through McMMO's annoying formatting, but I guess if it ain't broke don't fix it is how things go with McMMO with regards to VentureChat. 

Thanks for your response, I understand why this wouldn't be actually supported in the plugin.
