### ISSUE TITLE
Deficiencies: GUI (+Discord_Message), Party Chat, etc...

### ISSUE THREAD

**Issue by ColorsASD** [Aust1n46/VentureChat#46]
For discord texts, the GUI is completely wrong, the buttons work incorrectly or don't work at all, the colors are wrong, etc...

It would be nice if the GUI could be made editable. (Title, Player Info item, Cancel item, etc...)

And in the same way, put the texts of the Party into message.yml

In a party chat format, you could get PlaceholdersAPI support with several placeholders, so that we can at least see the player's rank in the chat.

And I really want "/party ban" and "/party join" to go away. 
"/party invite", "/party accept" and "/party deny" can be entered instead.
(Of course, the /party kick could still be used only by the host.)

The current party solution is quite ill-considered.

**Comment by Aust1n46** [comment]
Not planning to fix or do anything with the current party system other than just delete it.  I consider it a niche feature that is already covered well by other dedicated plugins.

It can be easily disabled in the commands.yml config and another party plugin used instead.

I can link suggested party plugins in the description if you have a preference.  I know mcmmo parties are popular on servers that use mcmmo.  (One of the biggest requests I received to allow commands to be disabled was to allow usage of mcmmo /party)



The GUI configurability is already covered by another open issue.  I also consider that a niche issue.  Haven't tested the Discord integration in a while.  There could be an issue with that that has cropped up.

**Comment by ColorsASD** [comment]
OK thank you. :)
