### ISSUE TITLE
ItemsAdder Emojis not working on VentureChat

### ISSUE THREAD

**Issue by ElMoha943** [Aust1n46/VentureChat#6]
My emojis are working correctly in every place (scoreboards, tab, names, msg) but the chat. They work fine in essentialsChat..
![imagen](https://user-images.githubusercontent.com/25410859/166934522-eaa1a028-cc3c-4e69-88c4-83e5ca2813c0.png)
also, placeholders work, as you can see the tag and crown that are form %img_name% work perfect, but the :name: doesnt

**Comment by Kas-tle** [comment]
ItemsAdder likely relies on some hacky solution to try to replace :admin: with the character it uses for ranks everywhere. Imo this is just another reason not to use ItemsAdder and make your own resource pack so that you understand what it's doing.

**Comment by ElMoha943** [comment]
> ItemsAdder likely relies on some hacky solution to try to replace :admin: with the character it uses for ranks everywhere. Imo this is just another reason not to use ItemsAdder and make your own resource pack so that you understand what it's doing.

If venturechat doesnt support it i ll just use another plugin that has the feature im looking for 😃
