### ISSUE TITLE
Cannot "/msg Player" without doing /messagetoggle first [BUG] 

### ISSUE THREAD

**Issue by LuluxClient** [Aust1n46/VentureChat#63]
I'm currently running on a velocity network on full premium and with bungee channels enabled. when trying to /msg someone it just sends 0 messages and the command sends 0 output. To fix it you need to do /messagetoggle and you will be able to send a message to someone.
Video: https://gyazo.com/275b072946cba16a2bd75d21011d906f

Config: https://mcpaste.io/0d244d09b6f06229 

Venturechat: 3.4.4
Protocollib: 5.0.0 b606
Server: 1.19.2
Velocity: 3.2.0 SNAPSHOT

**Comment by Aust1n46** [comment]
What version did you update from?  Message toggle was added 2 years ago and added a new data field.

It defaults to enabled, but not in very old versions of the plugin.  Your options are to edit the field in each player's data file or delete the PlayerData folder (with the server turned off) and let it regenerate.

**Comment by LuluxClient** [comment]
> What version did you update from? Message toggle was added 2 years ago and added a new data field.
> 
> It defaults to enabled, but not in very old versions of the plugin. Your options are to edit the field in each player's data file or delete the PlayerData folder (with the server turned off) and let it regenerate.

Latest and already deleted all of the player data (venturechat). I was never on an old version

**Comment by LuluxClient** [comment]
UPDATE: After updating the plugin the issue got fixed !
