### ISSUE TITLE
Use a custom player name

### ISSUE THREAD

**Issue by Internalizable** [Aust1n46/VentureChat#70]
Hi there!

I'm using your plugin for chat related activities, i have developed a plugin of my own where i set the display name of the user to a specific string (player.setDisplayName()). Yet the name is not reflecting in my chat, do you have any API i can hook into so i can change the display name?

**Comment by Aust1n46** [comment]
Are you using the {player_displayname} placeholder from PlaceholderAPI?  It should appear using this.  I don't modify displaynames.  I actually encourage users to use dedicated nickname plugins to customize player displaynames.

**Comment by Internalizable** [comment]
Yeah i was, just created a placeholder using PAPI to solve the issue and it seems that it has worked, thanks.
