### ISSUE TITLE
VentureChat cancelling AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by david1117dev** [Aust1n46/VentureChat#72]
Hello, I have a small problem. 2 month ago, I installed discordsrv with venturechat, it worked but now, it don't send messages to discord.

Plugin VentureChat v3.5.0 cancelled AsyncPlayerChatEvent (Bukkit) (author: david1117 | message: s)
[08:03:01 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: Global
[08:03:01 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User david1117 sent a message but it was not delivered to Discord because the chat event was canceled

Server version is 1.18.2

Logs https://mclo.gs/ANn9hdv

**Comment by Aust1n46** [comment]
VentureChat does cancel the AsyncPlayerChatEvent.  I fire my own event that DiscordSRV listens to and hooks into.

I don't know what settings you are using, but DiscordSRV supports VentureChat.

**Comment by vertanzil** [comment]
This is the same even if you run custom code in your own plugin and register the event, it cancels all AaSyncChatEvents.

**Comment by vertanzil** [comment]
This is also the same  @Aust1n46  if you run custom code that also interacts with the PlayerChat event, can you fix this or find a workaround?.

**Comment by joshwenke** [comment]
This is a really big issue for us as well. VentureChat stomps on our other chat plugins, even when their priorities are set to highest. Hoping it can be addressed

**Comment by Aust1n46** [comment]
I'm glad you were able to figure it out on your own.  I always appreciate that!

For future reference, the event firing order is listed in the documentation: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/EventPriority.html
