### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Evalutik** [Aust1n46/VentureChat#84]
Please, add an option of per-world channels

**Comment by Aust1n46** [comment]
If you set the channel distance to a large value, like 100000, it essentially becomes a per world channel.

**Comment by Evalutik** [comment]
> If you set the channel distance to a large value, like 100000, it essentially becomes a per world channel.
No, I mean let's say I need a channel that will only work in the spawn world, and in other worlds it will be ignored. if I just specify a large radius, messages will simply be sent to the world in which the player is located.

**Comment by 7hatGuyAJ** [comment]
Have you tried using permissions context within luckperms so people will only have perms to see and talk in that channel if within that world?

**Comment by Aust1n46** [comment]
Per world stuff is pretty niche with BungeeCord being the main focus.  You should be able to restrict channel access using a permissions plugin that supports per world permissions.

**Comment by Evalutik** [comment]
Okay, thanks
