### ISSUE TITLE
Unable to load correctly

### ISSUE THREAD

**Issue by GsTio86** [Aust1n46/VentureChat#94]
I'm running it on [Mohist 1.20.2](https://ci.codemc.io/job/MohistMC/job/Mohist-1.20.2/) but can't enable it
It will give error in console
Not sure what caused it, so I'll report back first

[Error log](https://haste.mohistmc.com/vecuhufaqo.css)

**Comment by manmadehuman** [comment]
I am getting the same error

**Comment by GsTio86** [comment]
Fixed in the latest mohist 1.20.2
